version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: goodfriend-db
    environment:
      POSTGRES_DB: goodfriend
      POSTGRES_USER: goodfriend
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: